
# ======================================================== #
# File automagically generated by GUI2Exe version 0.5.3
# Copyright: (c) 2007-2012 Andrea Gavana
# ======================================================== #

# Let's start with some default (for me) imports...

from setuptools import setup


# Ok, let's explain why I am doing that.
# Often, data_files, excludes and friends (but also resources)
# can be very long list of things, and this will clutter too much
# the setup call at the end of this file. So, I put all the big lists
# here and I wrap them using the textwrap module.

resources = ['/Users/Home/git/GNGSTA/GNGSTA/gui/svg/fileTags.svg', '/Users/Home/git/GNGSTA/GNGSTA/gui/svg/groupTags.svg',
             '/Users/Home/git/GNGSTA/GNGSTA/gui/svg/parallelCoordinates.svg',
             '/Users/Home/git/GNGSTA/GNGSTA/gui/svg/scatterplot.svg',
             '/Users/Home/git/GNGSTA/GNGSTA/gui/ui/Setup.ui',
             '/Users/Home/git/GNGSTA/GNGSTA/gui/ui/SingleVariant.ui']

includes = ['gzip', 'lxml._elementpath', 'lxml.etree', 'PySide.QtXml',
            'PySide.QtGui', 'PySide.QtCore']
excludes = ['Tkconstants', 'Tkinter', '_gtkagg', '_tkagg', 'bsddb',
            'curses', 'email', 'pywin.debugger', 'pywin.debugger.dbgcon',
            'pywin.dialogs', 'tcl']
packages = []
frameworks = []
dylib_excludes = []
datamodels = []

# PList custom code (if any) goes here
# No code for PList

# This is a place where the user custom code may go. You can do almost
# whatever you want, even modify the data_files, includes and friends
# here as long as they have the same variable name that the setup call
# below is expecting.

# No custom code added


# That's serious now: we have all (or almost all) the options py2app
# supports. I put them all even if some of them are usually defaulted
# and not used. Some of them I didn't even know about.

setup(

    app = [r'/Users/Home/git/GNGSTA/GNGSTA/compreheNGSive.py'],
    setup_requires=['py2app'],
    
    options = {"py2app": {"optimize": 0,
                          "includes": includes,
                          "excludes": excludes,
                          "packages": packages,
                          "dylib_excludes": dylib_excludes,
                          "frameworks": frameworks,
                          "datamodels": datamodels,
                          "resources": resources,
                          "iconfile": r'/Users/Home/git/GNGSTA/GNGSTA/gui/images/icon.icns',
                          "plist": None,
                          "extension": ".app",
                          "graph": False,
                          "dist_dir": r"dist",
                          "xref": False,
                          "no_strip": False,
                          "no_chdir": False,
                          "semi_standalone": False,
                          "argv_emulation": True,
                          "use_pythonpath": False,
                          "site_packages": False,
                          "prefer_ppc": False,
                          "debug_modulegraph": False,
                          "debug_skip_macholib": False
                         }
              },
    )

# This is a place where any post-compile code may go.
# You can add as much code as you want, which can be used, for example,
# to clean up your folders or to do some particular post-compilation
# actions.

# No post-compilation code added


# And we are done. That's a setup script :-D

